- imageUrl: "https://api.qrserver.com/v1/create-qr-code/?size=50x50&data=https://pr-$prNumber.company.com"
  url: "https://pr-$prNumber.company.com"

- label: "Preview"
  message: "PR $prNumber"
  color: "blue"
  url: "https://pr-$prNumber.company.com"

- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 500"

- label: "PR Size"
  message: "Medium"
  color: "yellow"
  when: "$additions > 200 && $additions < 500"

- message: "$payload.pull_request.user.login"
  color: "green"

- label: "Missing"
  message: "Test plan"
  color: "#ff0000"
  when: "$payload.pull_request.body.includes('Test plan') === false"

- label: "isDraft"
  message: "$isDraft"
  color: "Black"
  
- label: "Total Deletions"
  message: "$deletions"
  color: "#FF5733"

- label: "Total Additions"
  message: "$additions"
  color: "#30783E"
  
- label: "Total Commits"
  message: "$commits"
  color: "#0C2E8E"
  
- label: "Changed Files"
  message: "$changedFiles"
  color: "#A104C8"

- label: "Label"
  message: "Feature"
  when: "$labels.includes('Feature')"

- label: "Description length"
  message: "$payload.pull_request.body.length"
  color: "green"

- label: "Setup"
  message: "Completed"
  color: "green"
